version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "crates/exec-wasmtime"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "crates/shim-kvm"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "crates/shim-sgx"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "crates/sallyport"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "tests/rust_exec_tests"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "tests/rust_syscall_tests"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "tests/sev_attestation"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "tests/wasm/wasm_rust_tests"
  schedule:
    interval: "daily"
