[package]
name = "enarx"
version = "0.4.0"
edition = "2021"
description = "Tools for deploying WebAssembly into Enarx Keeps"
authors = ["The Enarx Project Developers"]
homepage = "https://enarx.dev/"
repository = "https://github.com/enarx/enarx"
license = "Apache-2.0"
keywords = ["sgx", "sev", "kvm", "tee"]
categories = ["os", "os::linux-apis", "network-programming", "hardware-support"]
exclude = [".github/"]

[features]
default = ["backend-kvm", "backend-sev", "backend-sgx"]
backend-kvm = ["kvm-bindings", "kvm-ioctls", "x86_64"]
backend-sev = ["backend-kvm", "ureq"]
backend-sgx = ["sgx", "ureq", "x86_64"]

# non-default features
gdb = ["gdbstub"]
dbg = []
disable-sgx-attestation = []

[dependencies]
anyhow = "1.0.56"
atty = "0.2"
bitflags = "1.2"
clap = { version = "3.1", features = ["env", "derive", "wrap_help"] }
colorful = "0.2"
const-default = { version = "1.0", features = [ "derive" ] }
dirs = "4.0"
env_logger = "0.9"
goblin = "0.5"
iocuddle = "0.1.1"
libc = "0.2"
log = "0.4"
lset = "0.3"
mmarinus = "0.2.1"
nbytes = "0.1"
once_cell = "1.10.0"
primordial = { version = "0.5", features = ["alloc"] }
protobuf = "2.22"
rand = "0.8"
sallyport = { version = "0.4.0", path = "crates/sallyport" }
semver = "1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
static_assertions = "1.1.0"
vdso = "0.2"

# optional dependencies
gdbstub = { version = "0.5.0", optional = true }
kvm-bindings = { version = "0.5", optional = true }
kvm-ioctls = { version = "0.11", optional = true }
sgx = { version = "0.4.0", features = ["openssl"], optional = true }
ureq = { version = "2.4.0", optional = true }
x86_64 = { version = "0.14.9", default-features = false, optional = true }

# binary dependencies
enarx-exec-wasmtime = { version = "0.4.0", path = "crates/exec-wasmtime", artifact = "bin", target = "x86_64-unknown-linux-musl" }
enarx-shim-kvm = { version = "0.4.0", path = "crates/shim-kvm", artifact = "bin", target = "x86_64-unknown-none" }
enarx-shim-sgx = { version = "0.4.0", path = "crates/shim-sgx", artifact = "bin", target = "x86_64-unknown-none" }

[build-dependencies]
protobuf-codegen-pure = "2.27"

[dev-dependencies]
process_control = "3.3"
serial_test = "0.6"
tempfile = "3.3.0"
wat = "1.0"

# binary dependencies
rust_exec_tests = { path = "tests/rust_exec_tests", artifact = "bin", target = "x86_64-unknown-linux-musl" }
rust_syscall_tests = { path = "tests/rust_syscall_tests", artifact = "bin", target = "x86_64-unknown-none" }
sev_attestation = { path = "tests/sev_attestation", artifact = "bin", target = "x86_64-unknown-linux-musl" }
wasm_rust_tests  = { path = "tests/wasm/wasm_rust_tests", artifact = "bin", target = "wasm32-wasi" }

[profile.dev]
strip = true

[profile.release]
incremental = false
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[profile.dev.package.rcrt1]
opt-level = 3

[workspace]
members = ["crates/*"]

[badges]
github = { repository = "enarx/enarx", workflow = "test" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "enarx/enarx" }
is-it-maintained-open-issues = { repository = "enarx/enarx" }
