[package]
name = "tcp_server"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
env_logger = { version = "0.8", default-features = false }
mio = { version = "0.8.2", features = ["os-poll", "net"], default-features = false }
